spring:
  application:
    name: SCP
  # DATASOURCE
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:dbSMCP"
    username: "sa"
    password: ""

  # H2 CLIENT
  h2:
    console:
      enabled: true
      path: "/h2-console"
  # JPA, SQL
  jpa:
    open-in-view: true
    database-platform: "org.hibernate.dialect.H2Dialect"
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        format_sql: false

